#!/usr/bin/env bash
set -e

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

libexec_path="$(abs_dirname "$0")"
export _FIKA_ROOT="$(abs_dirname "$libexec_path")"
export PATH="${libexec_path}:$PATH"

command="$1"
case "$command" in
"" | "-h" | "--help" )
  exec fika-help
  ;;
"-s" | "--search-class" )
  shift
  exec fika-search:class "$@"
  ;;
"-pa" | "--project-ant" )
  shift
  exec fika-project:ant "$@"
  ;;
"-pA" | "--project-android" )
  shift
  exec fika-project:android "$@"
  ;;
"-pS" | "--project-scala" )
  shift
  exec fika-project:scala "$@"
  ;;
"-pm" | "--project-maven" )
  shift
  exec fika-project:maven "$@"
  ;;
"-ps" | "--project-servlet" )
  shift
  exec fika-project:servlet "$@"
  ;;
"-pr" | "--project-rest" )
  shift
  exec fika-project:rest "$@"
  ;;
"-pj" | "--project-json" )
  shift
  exec fika-project:json "$@"
  ;;
"-a" | "--assembly" )
  shift
  exec fika-assembly "$@"
  ;;
"-l" | "--libs" )
  shift
  exec fika-libs "$@"
  ;;
"-sb" | "--spring-boot" )
  shift
  exec fika-spring:boot "$@"
  ;;
* )
  command_path="$(command -v "fika-$command" || true)"
  if [ ! -x "$command_path" ]; then
    echo "fika: no such command \`$command'" >&2
    exit 1
  fi

  shift
  exec "$command_path" "$@"
  ;;
esac
