#!/usr/bin/env bash
# Usage: fika assembly | -a | --assembly fully.qualified.class.Name
# Summary: builds an assembly with every jar dependency and a Name.sh shell script
# Help: this command builds an assembly with every jar dependency and a  shell script

CURRDIR=$(pwd)
cd ${CURRDIR}

MAIN_CLASS=$1
ONLY_CLASS=$(echo ${MAIN_CLASS}| sed -e 's/\./\//g' | xargs basename)
JARDIR=${CURRDIR}/lib
SCRIPTSDIR=${CURRDIR}/script
SCRIPT_FILE=${SCRIPTSDIR}/${ONLY_CLASS}".sh"
#SCRIPT_FILE=${SCRIPTSDIR}/${ONLY_CLASS}

progname_depends_deb=
progname_depends_rpm=
progname_version=
progname_description=


function fpmpackage_deb(){
        fpm --architecture all -s dir -t deb --depends "$progname_depends_deb" -C ${CURRDIR}/dist --name "$progname" --version "$progname_version" --description "$progname_description"
}
function fpmpackage_osxpkg(){
        fpm --architecture all -s dir -t osxpkg --depends "$progname_depends_rpm" -C ${CURRDIR}/dist --name "$progname" --version "$progname_version" --description "$progname_description"
}
function fpmpackage_rpm(){
        fpm --architecture all -s dir -t rpm --depends "$progname_depends_rpm" -C ${CURRDIR}/dist --name "$progname" --version "$progname_version" --description "$progname_description"
}



if [ $# -ne 1 ]; then
        echo "Bad param numbers: see manual"
        exit;
else
	test -d ${JARDIR} || mkdir -p ${JARDIR}
	test -d ${SCRIPTSDIR} || mkdir -p ${SCRIPTSDIR}

	mvn  dependency:build-classpath -Dmdep.outputFile=${CURRDIR}/classpath.txt 2>&1>/dev/null

	for j in $(cat ${CURRDIR}/classpath.txt | sed -e 's/\:/ /g'); do
		cp $j ${JARDIR}
	done

	echo '#! /bin/bash' > ${SCRIPT_FILE}
	echo "" >> ${SCRIPT_FILE}
	echo "cd \$(dirname \$0)" >> ${SCRIPT_FILE}
	echo "PROG_VERSION=x.y.z" >> ${SCRIPT_FILE}
	echo "LIBDIR=./lib" >> ${SCRIPT_FILE}
	echo "TARGETDIR=./target" >> ${SCRIPT_FILE}
	echo "TARGET_JAR=${ONLY_CLASS}-\${PROG_VERSION}.jar" >> ${SCRIPT_FILE}
	echo "" >> ${SCRIPT_FILE}

	cd ${JARDIR}
	for l in *.jar; do
		echo "CP=\${CP}:\${LIBDIR}/${l}">> ${SCRIPT_FILE}
	done
	echo "CP=\${CP}:\${TARGETDIR}/\${TARGET_JAR}">> ${SCRIPT_FILE}
	echo "" >> ${SCRIPT_FILE}
	echo "java -cp \${CP} ${MAIN_CLASS}" >> ${SCRIPT_FILE}
	chmod 755 ${SCRIPT_FILE}
fi
